### ISSUE TITLE
Error while running FullNetworkSetGenerator with .nup files

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/XTMF#25]
I have attempted to run Full Network Set Generator via XTMF with a .nup file assigned to one time period. I was able to set this up in Modeller, but the XTMF side is failing:

EMME Parameter Error: The module "tmg.network_editing.full_network_set_generator" was executed with the wrong number of arguments or of invalid types.
   at TMG.Emme.ModellerController.WaitForEmmeResponce(String& returnValue, Action`1 updateProgress) in C:\Documents\GITXTMF\Code\TMG.Emme\ModellerController.cs:line 274
   at TMG.Emme.ModellerController.Run(String macroName, String arguments, Action`1 progressUpdate, String& returnValue) in C:\Documents\GITXTMF\Code\TMG.Emme\ModellerController.cs:line 365
   at TMG.Emme.ModellerController.Run(String macroName, String arguments) in C:\Documents\GITXTMF\Code\TMG.Emme\ModellerController.cs:line 338
   at TMG.Emme.ExecuteToolsFromModellerResource.Start() in C:\Documents\GITXTMF\Code\TMG.Emme\ExecuteToolsFromModellerResource.cs:line 43
   at Tasha.Utilities.BasicTravelDemandModel.Start() in C:\Documents\GITXTMF\Tasha\Utilities\BasicTravelDemandModel.cs:line 83
   at XTMF.XTMFRun.OurRun() in C:\Documents\GITXTMF\Code\XTMF1.1\XTMFRun.cs:line 334

One possibility: the code does not like that I put a .nup file in only one of the time periods.

I've attached the model system I used.

[NetworkGenSnippet08-22.txt](https://github.com/TravelModellingGroup/XTMF/files/431116/NetworkGenSnippet08-22.txt)

**Comment by mattaustin222** [comment]
Tested it with a .nup file in all time periods. This is not the issue.

**Comment by JamesVaughan** [comment]
I've identified where the problem seems to be when passing the file name it ends up unquoting the parameter being passed instead of being contained in the larger parameter string.  I'll build a test environment for this tomorrow.

**Comment by JamesVaughan** [comment]
c7c17e4a796a3e6a194257287722be7e75a6be43  contains a potential fix for this issue.

**Comment by JamesVaughan** [comment]
After the patch for the TMG toolbox it is now working.
